site_name: TransSoul-Wiki
repo_url: https://github.com/TransSoul/Wiki
repo_name: Github Repo
site_author: TransSoul Team
site_description: 一個為跨性別者提供服務的知識平台
edit_uri: blob/main/docs/

plugins:
  - search
  - include_dir_to_nav
  - git-committers:
      repository: TransSoul/Wiki
      branch: main

theme: 
  font:
    text: Noto Sans Simplified Chinese
  custom_dir: overrides
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: pink
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: pink
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

      
  icon:
    repo: fontawesome/brands/github
  language: zh-TW
  logo: logo.jpg
  favicon: logo.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.action.edit
    - content.action.view

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.details
  - admonition
  - toc:
      permalink: ¶

copyright: Copyright &copy; 2024 - 2024 TransSoul Team (<a href="https://github.com/TransSoul/Wiki/blob/main/LICENSE">CC-BY-SA-4.0</a>)