import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/markdown-page',
    component: ComponentCreator('/markdown-page', '3d7'),
    exact: true
  },
  {
    path: '/search',
    component: ComponentCreator('/search', '5de'),
    exact: true
  },
  {
    path: '/docs',
    component: ComponentCreator('/docs', '911'),
    routes: [
      {
        path: '/docs',
        component: ComponentCreator('/docs', '673'),
        routes: [
          {
            path: '/docs',
            component: ComponentCreator('/docs', 'f34'),
            routes: [
              {
                path: '/docs/性別焦慮（GD）/gd',
                component: ComponentCreator('/docs/性別焦慮（GD）/gd', '0bf'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/性別焦慮（GD）/transwomen',
                component: ComponentCreator('/docs/性別焦慮（GD）/transwomen', 'e8a'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/contribute',
                component: ComponentCreator('/docs/contribute', '05e'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/intro',
                component: ComponentCreator('/docs/intro', '643'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '/',
    component: ComponentCreator('/', '2e1'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
