name: Pages Check
run-name: ${{ github.actor }} is checking pages deployment 🚀
on:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - name: Install dependencies
      run: npm install
    - name: Give execute permission to vitepress
      run: chmod +x ./node_modules/.bin/vitepress
    - name: Build Pages
      run: npx vitepress build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist
        publish_branch: gh-pages
