name: Comment on Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const { owner, repo } = context.repo;
            await github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: '感谢您的反馈！我们会尽快处理。'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
