name: Comment on Issue

on:
  issues:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 使用 GitHub App 进行身份验证
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_SECRET }}
          owner: ${{ github.repository_owner }}
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `感谢你的问题！  https://github.com/TransSoul/Wiki/issues/${context.issue.number}`
            });